// <auto-generated />
using System;
using BatalhaNaval.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BatalhaNaval.Infrastructure.Migrations
{
    [DbContext(typeof(BatalhaNavalDbContext))]
    [Migration("20260201175159_FinalRankingSystem")]
    partial class FinalRankingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiDifficulty")
                        .HasColumnType("text")
                        .HasColumnName("ai_difficulty");

                    b.Property<Guid>("CurrentTurnPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_turn_player_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime>("LastMoveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_move_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_mode");

                    b.Property<string>("Player1Board")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("player1_board_json");

                    b.Property<int>("Player1Hits")
                        .HasColumnType("integer")
                        .HasColumnName("player1_hits");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player1_id");

                    b.Property<string>("Player2Board")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("player2_board_json");

                    b.Property<int>("Player2Hits")
                        .HasColumnType("integer")
                        .HasColumnName("player2_hits");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player2_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.Medal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medals");
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<string>("EarnedMedalCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("medals_json");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer")
                        .HasColumnName("max_streak");

                    b.Property<int>("RankPoints")
                        .HasColumnType("integer")
                        .HasColumnName("rank_points");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("UserId");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.UserMedal", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("MedalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "MedalId");

                    b.HasIndex("MedalId");

                    b.ToTable("UserMedals");
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.PlayerProfile", b =>
                {
                    b.HasOne("BatalhaNaval.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("BatalhaNaval.Domain.Entities.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.UserMedal", b =>
                {
                    b.HasOne("BatalhaNaval.Domain.Entities.Medal", "Medal")
                        .WithMany()
                        .HasForeignKey("MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatalhaNaval.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BatalhaNaval.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
